---
detectors:
  IrresponsibleModule:
    enabled: false

  DataClump:
    max_copies: 3
    min_clump_size: 3

directories:
  "db/migrate":
    FeatureEnvy:
      enabled: false
    TooManyStatements:
      enabled: false
    UncommunicativeVariableName:
      enabled: false