AllCops:
  TargetRubyVersion: 3.2.2
  NewCops: enable
  Exclude:
    - bin/**/*
    - config/environments/development.rb
    - db/**/*
    - db/schema.rb
    - vendor/**/*

Style/Documentation:
  Enabled: false
