version: '3.8'

services:
  db:
    image: postgres:13
    container_name: personal_db
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test 
    volumes:
      - personal_postgres_data:/var/lib/postgresql/data
    command:
      "postgres -c 'max_connections=500'"
    ports:
      - "5432:5432"    

  personal:
    build: .
    command: rails server -b 0.0.0.0
    volumes:
      - ".:/myapp"
    ports:
      - "3000:3000"
    depends_on:
      - db  

volumes:
  personal_postgres_data:
