default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: test
  password: test
  host: db

development:
  <<: *default
  database: personal_development

test:
  <<: *default
  database: personal_test

production:
  <<: *default
  database: personal_production
  username: test
  password: test