default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>

development:
  <<: *default
  database: mydatabase

test:
  <<: *default
  database: mydatabase_test

production:
  <<: *default
  database: mydatabase_production
  username: mydatabase_production
  password: <%= ENV['MYDATABASE_PRODUCTION_PASSWORD'] %>