default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>  
  host: <%= ENV["POSTGRES_HOST"] %>
  port: 5432

development:
  <<: *default
  database: <%= ENV["DEVELOPMENT_DATA_BASE"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_USER"] %>

test:
  <<: *default
  database: <%= ENV["TEST_DATA_BASE"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

production:
  <<: *default
  database: <%= ENV["PRODUCTION_DATA_BASE"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>